import { z } from 'zod'

// Media type union — aligned with DB CHECK constraint
export type MediaType = 'image' | 'video'

/** A NEW media item selected by the user — not yet uploaded to Storage */
export interface NewMediaItem {
  kind: 'new'
  /** Unique local key generated by crypto.randomUUID() */
  key: string
  file: File
  /** Object URL for thumbnail preview — revoke when item is removed */
  preview_url: string
  media_type: MediaType
  is_cover: boolean
  order_index: number
}

/** An EXISTING media item loaded from the database */
export interface ExistingMediaItem {
  kind: 'existing'
  id: string
  url: string
  thumbnail_url: string | null
  media_type: MediaType
  is_cover: boolean
  order_index: number
}

/** Union of new (not yet uploaded) and existing (already in DB) media items */
export type MediaItem = NewMediaItem | ExistingMediaItem

/** Unique identifier for drag-and-drop — new items use key, existing use id */
export function getMediaItemId(item: MediaItem): string {
  return item.kind === 'new' ? item.key : item.id
}

/** Post form field values — validated by Zod */
export const PostFormSchema = z.object({
  title: z
    .string()
    .transform((s) => s.trim())
    .pipe(z.string().min(1, 'Naslov je obvezen').max(255, 'Naslov je predolg (max 255 znakov)')),
  content: z.string().optional(),
  excerpt: z.string().max(500, 'Povzetek je predolg (max 500 znakov)').optional(),
  category: z
    .string()
    .transform((s) => s.trim())
    .pipe(z.string().min(1, 'Kategorija je obvezna').max(100)),
})

export type PostFormValues = z.infer<typeof PostFormSchema>

/** Maximum number of media files allowed per post */
export const MAX_MEDIA_FILES = 10

/** Maximum file size for images (10 MB) */
export const MAX_IMAGE_SIZE = 10 * 1024 * 1024

/** Maximum file size for videos (100 MB) */
export const MAX_VIDEO_SIZE = 100 * 1024 * 1024

/** Allowed MIME types for image uploads */
export const ALLOWED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
]

/** Allowed MIME types for video uploads */
export const ALLOWED_VIDEO_TYPES = ['video/mp4', 'video/quicktime', 'video/webm']

/** All allowed media MIME types */
export const ALLOWED_MEDIA_TYPES = [...ALLOWED_IMAGE_TYPES, ...ALLOWED_VIDEO_TYPES]
